import { execFileSync } from 'child_process'
import { DEFAULT_TERMINAL_COLS, DEFAULT_TERMINAL_ROWS } from '../constants'
import {
  TMUX_SOCKET,
  detectTmux,
  getTmuxConfigPath,
  isValidTmuxName,
  ptyManager
} from '../pty-manager'
import type { RemoteAttachInfo, RemoteAttachMode } from '../../shared/remote-protocol'

/**
 * Validated tmux attach descriptors for remote clients.
 *
 * The client never composes a shell command: it names a session id and gets
 * back a ready-to-run argv. Everything that could reach an argv is checked
 * here first, because the `clave` socket is user-attachable and a `clave-`
 * prefix is not proof that Clave created the session (see the comment on
 * `listAdoptableTmuxSessions` in pty-manager.ts).
 */

/** Client flags for `attach-session -f`, per mode. P0-A measured all three.
 *
 *  `ignore-size` excludes the client from window-size calculation, so a small
 *  iPad attaching cannot reflow the Mac's pane under `window-size latest`. It
 *  is a guard, not the mechanism: a client narrower than the window is CLIPPED
 *  to its own width, so a mirror must also size its pty to `cols`/`rows` below.
 *  Takeover deliberately omits it and lets tmux reflow the window to follow. */
const MODE_FLAGS: Record<RemoteAttachMode, string[]> = {
  mirror: ['ignore-size'],
  takeover: [],
  watch: ['read-only', 'ignore-size']
}

export interface SessionTmuxFacts {
  tmuxName: string | null
  remotable: boolean
  reason?: string
}

/**
 * The tmux facts about a session, which live in main and are absent from the
 * renderer's model. `reason` is shown in the client UI, so it says what is
 * true about the session rather than listing what it lacks.
 */
export function getSessionTmuxFacts(sessionId: string): SessionTmuxFacts {
  const session = ptyManager.getSession(sessionId)
  if (!session) {
    return { tmuxName: null, remotable: false, reason: 'This session is closed on the Mac.' }
  }
  if (!session.tmuxName) {
    return {
      tmuxName: null,
      remotable: false,
      reason:
        'This session started with tmux mode off. Sessions need tmux to be reachable from another device.'
    }
  }
  if (!isValidTmuxName(session.tmuxName)) {
    // Belt and braces: names are generated by Clave, so a mismatch means the
    // session record was tampered with. Refuse rather than pass it to an argv.
    return {
      tmuxName: null,
      remotable: false,
      reason: 'Clave does not recognise this session as one of its own tmux sessions.'
    }
  }
  if (!session.alive) {
    return {
      tmuxName: session.tmuxName,
      remotable: false,
      reason: 'This session has exited. Start it again to reach it from another device.'
    }
  }
  if (!detectTmux()) {
    return {
      tmuxName: session.tmuxName,
      remotable: false,
      reason: 'tmux is missing from this Mac, so remote attach is unavailable.'
    }
  }
  return { tmuxName: session.tmuxName, remotable: true }
}

/**
 * The host window's CURRENT geometry. A mirror client must match it exactly:
 * anything narrower silently receives a clipped grid (P0-A test 6), and a stale
 * mirror stays clipped until it resyncs, which is why the server pushes a
 * `geometry` event on every host resize.
 *
 * `execFileSync` rather than `execSync`: the latter goes through `/bin/sh`,
 * which is the packaged-app PATH hazard documented in CLAUDE.md. `tmuxPath` is
 * already resolved against the login shell by `detectTmux`, and passing argv
 * directly means the session name is never shell-parsed.
 */
function readWindowGeometry(tmuxPath: string, tmuxName: string): { cols: number; rows: number } {
  try {
    const out = execFileSync(
      tmuxPath,
      [
        '-L',
        TMUX_SOCKET,
        'display-message',
        '-p',
        '-t',
        tmuxName,
        '#{window_width}x#{window_height}'
      ],
      { encoding: 'utf-8', timeout: 2000 }
    )
    const [cols, rows] = out.trim().split('x').map(Number)
    if (Number.isInteger(cols) && cols > 0 && Number.isInteger(rows) && rows > 0) {
      return { cols, rows }
    }
  } catch {
    /* server gone or the window vanished between the check and here */
  }
  // A wrong-but-sane size still attaches; the next geometry event corrects it.
  return { cols: DEFAULT_TERMINAL_COLS, rows: DEFAULT_TERMINAL_ROWS }
}

/**
 * Build the descriptor for one attach. Throws with a user-facing message when
 * the session cannot be attached to, so the caller can hand the text straight
 * to the client.
 */
export function buildAttachInfo(sessionId: string, mode: RemoteAttachMode): RemoteAttachInfo {
  const facts = getSessionTmuxFacts(sessionId)
  if (!facts.remotable || !facts.tmuxName) {
    throw new Error(facts.reason ?? 'This session is not reachable from another device.')
  }
  const tmuxName = facts.tmuxName

  const tmuxPath = detectTmux()
  if (!tmuxPath) {
    throw new Error('tmux is missing from this Mac, so remote attach is unavailable.')
  }

  const configPath = getTmuxConfigPath()
  if (!configPath) {
    // getTmuxConfigPath returns '' when it could not write the file. Attaching
    // without `-f` would pick up the user's ~/.tmux.conf, whose bindings and
    // `destroy-unattached` could kill the very session being attached to.
    throw new Error('Clave could not write its tmux config, so remote attach is unavailable.')
  }

  const flags = MODE_FLAGS[mode] ?? MODE_FLAGS.mirror
  const { cols, rows } = readWindowGeometry(tmuxPath, tmuxName)

  // The two `-f`s are different flags: the first is tmux's config file, the
  // second is attach-session's client flags. Order matters, tmux reads the
  // config one before the command.
  const argv = [
    tmuxPath,
    '-u',
    '-L',
    TMUX_SOCKET,
    '-f',
    configPath,
    'attach-session',
    '-t',
    tmuxName,
    ...(flags.length > 0 ? ['-f', flags.join(',')] : [])
  ]

  return {
    sessionId,
    tmuxName,
    socket: TMUX_SOCKET,
    tmuxPath,
    configPath,
    cols,
    rows,
    flags,
    argv
  }
}
